worker_processes auto;

events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    # -------- UPSTREAMS (xarxa interna Docker) --------
    upstream backend_upstream {
        server backend:5000;
    }

        upstream frontend_upstream {
        server frontend:3000;
    }

    server {
        listen 80;
        server_name _;

        # Capçaleres de seguretat bàsiques
        add_header X-Frame-Options SAMEORIGIN always;
        add_header X-Content-Type-Options nosniff always;

        # API → backend
        location /api/ {
            proxy_pass         http://backend_upstream;
            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        # Healthcheck del backend
        location /health {
            proxy_pass http://backend_upstream/health;
        }

        # Tota la resta → frontend
        location / {
            proxy_pass         http://frontend_upstream;
            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }
}
